import { CalendarDays, CheckCircle2, Clock3, CircleAlert, Sparkles, UserRoundPen } from 'lucide-react'

export const schedulePostsData = {
  stats: [
    {
      id: 'scheduled-count',
      label: 'Scheduled',
      value: 128,
      hint: 'Next 7 days',
      icon: CalendarDays,
      toneClassName: 'bg-blue-50 text-blue-700',
    },
    {
      id: 'ready-to-approve',
      label: 'Ready to Approve',
      value: 34,
      hint: 'Awaiting review',
      icon: Clock3,
      toneClassName: 'bg-amber-50 text-amber-700',
    },
    {
      id: 'published-today',
      label: 'Published Today',
      value: 21,
      hint: 'Live now',
      icon: CheckCircle2,
      toneClassName: 'bg-emerald-50 text-emerald-700',
    },
    {
      id: 'needs-attention',
      label: 'Needs Attention',
      value: 5,
      hint: 'Failures / retries',
      icon: CircleAlert,
      toneClassName: 'bg-rose-50 text-rose-700',
    },
  ],
  filters: [
    {
      id: 'platform-filter',
      label: 'Platform',
      options: ['All Platforms', 'facebook', 'instagram', 'linkedin', 'x'],
      value: 'All Platforms',
    },
    {
      id: 'status-filter',
      label: 'Status',
      options: ['All Statuses', 'scheduled', 'draft', 'ready_for_review', 'failed'],
      value: 'All Statuses',
    },
    {
      id: 'date-filter',
      label: 'Date Range',
      options: ['Next 7 Days', 'Next 30 Days', 'This Month'],
      value: 'Next 7 Days',
    },
  ],
  posts: [
    {
      id: 'schedule-post-1',
      dateTime: 'Jul 19, 09:00 AM',
      platform: 'facebook',
      contentPreview: 'Launching the latest AI automation workflow for enterprise teams.',
      status: 'scheduled',
      assignedTo: 'Maya Chen',
      platformAccent: 'bg-blue-50 text-blue-700',
      statusAccent: 'bg-blue-50 text-blue-700',
    },
    {
      id: 'schedule-post-2',
      dateTime: 'Jul 19, 01:30 PM',
      platform: 'linkedin',
      contentPreview: 'A deeper look at structured content approval for distributed teams.',
      status: 'ready_for_review',
      assignedTo: 'Jordan Lee',
      platformAccent: 'bg-sky-50 text-sky-700',
      statusAccent: 'bg-amber-50 text-amber-700',
    },
    {
      id: 'schedule-post-3',
      dateTime: 'Jul 20, 10:15 AM',
      platform: 'instagram',
      contentPreview: 'Visual story sequence about multi-channel campaign orchestration.',
      status: 'draft',
      assignedTo: 'Ava Patel',
      platformAccent: 'bg-pink-50 text-pink-700',
      statusAccent: 'bg-slate-100 text-slate-600',
    },
    {
      id: 'schedule-post-4',
      dateTime: 'Jul 20, 03:45 PM',
      platform: 'x',
      contentPreview: 'Short-form thread outlining today’s performance insights and wins.',
      status: 'failed',
      assignedTo: 'Logistics Bot',
      platformAccent: 'bg-slate-100 text-slate-700',
      statusAccent: 'bg-rose-50 text-rose-700',
    },
    {
      id: 'schedule-post-5',
      dateTime: 'Jul 21, 08:30 AM',
      platform: 'linkedin',
      contentPreview: 'Thought leadership post focused on B2B growth operations.',
      status: 'scheduled',
      assignedTo: 'Noah Kim',
      platformAccent: 'bg-sky-50 text-sky-700',
      statusAccent: 'bg-blue-50 text-blue-700',
    },
  ],
  quickActions: [
    {
      id: 'bulk-upload',
      label: 'Bulk Upload',
      helper: 'Import CSV content batches',
      icon: UserRoundPen,
    },
    {
      id: 'ai-draft',
      label: 'Generate with AI',
      helper: 'Create ready-to-edit drafts',
      icon: Sparkles,
    },
  ],
}