import { Link2, TriangleAlert, Clock3 } from 'lucide-react'

export const connectorsData = {
  summaryCards: [
    {
      id: 'active-channels',
      label: 'Total Active',
      value: '12 Channels',
      icon: Link2,
      accentClassName: 'bg-blue-50 text-blue-700',
    },
    {
      id: 'action-needed',
      label: 'Action Needed',
      value: '2 Expired',
      icon: TriangleAlert,
      accentClassName: 'bg-rose-50 text-rose-700',
    },
    {
      id: 'sync-delay',
      label: 'Avg. Sync Delay',
      value: '1.2 Minutes',
      icon: Clock3,
      accentClassName: 'bg-sky-50 text-sky-700',
    },
  ],
  connectors: [
    {
      id: 'linkedin-global',
      platform: 'linkedin',
      platformLabel: 'LinkedIn',
      badge: 'Corporate',
      status: 'connected',
      statusMessage: 'Connected as Acme Corp Global',
      lastSynced: '4 mins ago',
      requiresPageId: false,
      pageIdPlaceholder: 'Not required',
      config: {
        appId: 'lkd-prod-4228',
        appSecret: '••••••••••••',
        accessToken: '••••••••••••••••',
        pageId: '',
        callbackUrl: 'https://api.acme.com/webhooks/linkedin',
        notes: 'Primary B2B publishing connector for corporate updates.',
      },
    },
    {
      id: 'twitter-x',
      platform: 'twitter',
      platformLabel: 'Twitter/X',
      badge: null,
      status: 'reconnect',
      statusMessage: 'Session expired. Reconnect now to resume publishing.',
      lastSynced: '2 days ago',
      requiresPageId: false,
      pageIdPlaceholder: 'Not required',
      config: {
        appId: 'x-api-1051',
        appSecret: '••••••••••',
        accessToken: '••••••••••••••',
        pageId: '',
        callbackUrl: 'https://api.acme.com/webhooks/x',
        notes: 'Token refresh required after account revalidation.',
      },
    },
    {
      id: 'instagram-main',
      platform: 'instagram',
      platformLabel: 'Instagram',
      badge: null,
      status: 'connected',
      statusMessage: 'Connected as @acme_official',
      lastSynced: '12 mins ago',
      requiresPageId: false,
      pageIdPlaceholder: 'Not required',
      config: {
        appId: 'ig-main-8892',
        appSecret: '••••••••••••',
        accessToken: '••••••••••••••••',
        pageId: '',
        callbackUrl: 'https://api.acme.com/webhooks/instagram',
        notes: 'Media-first publishing with story and reel support.',
      },
    },
    {
      id: 'facebook-solutions',
      platform: 'facebook',
      platformLabel: 'Facebook',
      badge: null,
      status: 'connected',
      statusMessage: 'Connected as Acme Tech Solutions',
      lastSynced: '1 hour ago',
      requiresPageId: true,
      pageIdPlaceholder: 'Facebook Page ID',
      config: {
        appId: 'fb-solution-3104',
        appSecret: '••••••••••••',
        accessToken: '••••••••••••••••',
        pageId: '2148830192921',
        callbackUrl: 'https://api.acme.com/webhooks/facebook',
        notes: 'Primary brand page for product and company updates.',
      },
    },
    {
      id: 'tiktok-disconnected',
      platform: 'tiktok',
      platformLabel: 'TikTok',
      badge: null,
      status: 'disconnected',
      statusMessage: 'Disconnected. Connect to resume short-form publishing.',
      lastSynced: 'Never',
      requiresPageId: false,
      pageIdPlaceholder: 'Not required',
      config: {
        appId: 'ttk-core-7710',
        appSecret: '',
        accessToken: '',
        pageId: '',
        callbackUrl: 'https://api.acme.com/webhooks/tiktok',
        notes: 'Integration onboarding pending for this channel.',
      },
    },
  ],
}