import { CalendarDays, CheckCircle2, CircleAlert, Clock3, Sparkles, Users2 } from 'lucide-react'

export const dashboardData = {
  stats: [
    {
      id: 'scheduled-posts',
      label: 'Scheduled Posts',
      value: 148,
      badge: '+12%',
      icon: CalendarDays,
      badgeClassName: 'bg-emerald-50 text-emerald-600',
      cardClassName: 'bg-white',
    },
    {
      id: 'published-today',
      label: 'Published Today',
      value: 24,
      badge: 'Active',
      icon: CheckCircle2,
      badgeClassName: 'bg-emerald-50 text-emerald-600',
      cardClassName: 'bg-white',
    },
    {
      id: 'pending-approval',
      label: 'Pending Approval',
      value: 8,
      badge: 'Pending',
      icon: Clock3,
      badgeClassName: 'bg-amber-50 text-amber-600',
      cardClassName: 'bg-white',
    },
    {
      id: 'connected-accounts',
      label: 'Connected Accounts',
      value: 12,
      badge: 'Max 20',
      icon: Users2,
      badgeClassName: 'bg-slate-100 text-slate-500',
      cardClassName: 'bg-white',
    },
    // {
    //   id: 'failed-posts',
    //   label: 'Failed Posts',
    //   value: 2,
    //   badge: 'Critical',
    //   icon: CircleAlert,
    //   badgeClassName: 'bg-rose-50 text-rose-600',
    //   cardClassName: 'bg-white',
    // },
    // {
    //   id: 'ai-generated',
    //   label: 'AI Generated',
    //   value: 412,
    //   badge: 'AI Opt',
    //   icon: Sparkles,
    //   badgeClassName: 'bg-blue-50 text-blue-600',
    //   cardClassName: 'bg-blue-50/90',
    // },
  ],
  publishingActivity: {
    labels: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'],
    data: [70, 110, 140, 95, 155, 125, 78, 118, 150, 170, 120, 88],
  },
  upcomingPosts: [
    {
      id: 'post-1',
      dateTime: 'Oct 24, 09:00 AM',
      platform: 'facebook',
      contentPreview: 'The future of AI-driven content scheduling is here.',
      status: 'ready',
    },
    {
      id: 'post-2',
      dateTime: 'Oct 24, 02:30 PM',
      platform: 'linkedin',
      contentPreview: 'Thrilled to announce our next enterprise workflow update.',
      status: 'ready',
    },
    {
      id: 'post-3',
      dateTime: 'Oct 25, 11:15 AM',
      platform: 'instagram',
      contentPreview: 'Behind the scenes: how we automate campaign approvals.',
      status: 'drafting',
    },
  ],
  pendingApprovals: [
    {
      id: 'approval-1',
      title: 'Q4 Strategy Post',
      description: 'LinkedIn · Today, 11:00 AM',
      actionLabel: 'Approve',
      accent: 'bg-blue-600',
    },
    {
      id: 'approval-2',
      title: 'Community Update #12',
      description: 'Twitter · Oct 26, 08:00 PM',
      actionLabel: 'Approve',
      accent: 'bg-blue-600',
    },
  ],
  recentActivity: [
    {
      id: 'activity-1',
      title: 'Post Successfully Published',
      description: 'Instagram Carousel "Product Launch" is now live.',
      time: '2 mins ago',
      tone: 'bg-blue-600',
    },
    {
      id: 'activity-2',
      title: 'Connection Failed',
      description: 'TikTok account "Global_Corp" requires re-authentication.',
      time: '45 mins ago',
      tone: 'bg-rose-600',
    },
    {
      id: 'activity-3',
      title: 'Account Connected',
      description: 'LinkedIn Marketing Account "Americas_Hub" linked.',
      time: '2 hours ago',
      tone: 'bg-emerald-500',
    },
  ],
}